apiVersion: apps/v1
kind: Deployment
metadata:
  name: drugserdeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MailOrderPharmacy_DrugService
  template:
    metadata:
      labels:
        app: MailOrderPharmacy_DrugService
    spec:
      containers:
      - name: drugrepos
        image: mailorderpharmacycr.azurecr.io/drugrepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: asconfigsn

---
apiVersion: v1
kind: Service
metadata:
  name: mailorderpharmacy_drugservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: MailOrderPharmacy_DrugService